<?php

	$about = array(
		'name' => 'Русский',
		'author' => array(
			'name' => 'Andrey Lubinov',
			'email' => 'andrey.lubinov@gmail.com',
			'website' => false
		),
		'release-date' => '2010-04-09'
	);


	/*
	 * EXTENSION: File Manager
	 * Localisation strings
	 */

	$dictionary = array(

		'File Manager' =>
		'Менеджер файлов',

		'Symphony &ndash; File Manager' =>
		'Symphony &ndash; Менеджер Файлов',

		'Symphony &ndash; File Manager &ndash; ' =>
		'Symphony &ndash; Менеджер Файлов &ndash; ',

		'Symphony &ndash; File Manager &ndash; Untitled' =>
		'Symphony &ndash; Менеджер файлов &ndash; Безымянный',

		'Upload, Edit and manage files and folders.' =>
		'Загрузка, редактирование и управление файлами и каталогами',

		'Backup' =>
		'Резервная копия',

		'This path is relative to the root Symphony installation folder, <code>%s</code>' =>
		'Путь относительно каталога, в который установлена Symphony',

		'Root Browse Location' =>
		'Корневой каталог',

		'Archive Name' =>
		'Название архива',

		'Default filename for archives generated by File Manager' =>
		'Имя файла по умолчанию для архивов, созданных файловым менеджером',

		' Show Hidden Files and Folders' =>
		'Отображать скрытые файлы и каталоги',

		'Hidden files will not be included in archives unless this is checked.' =>
		'Скрытые файлы не будут включаться в архивы если эта опци не отмечена',

		'The file you requested, <code>%s</code>, does not exist.' =>
		'Файл <code>%s</code> не существует.',

		'Download' =>
		'Загрузить',

		'%s could not be deleted as is still contains files.' =>
		'Невозможно удалить %s потому, что там все еще есть файлы',

		'New Directory' =>
		'Новый каталог',

		'New File' =>
		'Новый файл',

		'Upload File' =>
		'Загрузить файл',

		'This directory is not writable' =>
		'Каталог не доступен для записи',

		'Size' =>
		'Размер',

		'Permissions' =>
		'Права доступа',

		'Modified' =>
		'Изменен',

		'Available Actions' =>
		'Доступные действия',

		'Archive' =>
		'Архивировать',

		'Upload Existing File' =>
		'Загрузка существующего файла',

		'File' =>
		'Файл',

		'Create New Directory' =>
		'Создание нового каталога',

		'Create New File' =>
		'Создание нового файла',

		'Contents' =>
		'Содержимое',

		'%s updated successfully' =>
		'%s успешно обновлен',

		'Folder' =>
		'Каталог',

		'Preview' =>
		'Просмотр',

		'Editor' =>
		'Редактор',

		'Delete this ' =>
		'Удалить этот ',

		'The server does not have permission to edit this file.' =>
		'У сервера нет прав доступа для редактирования этого файла.',

	);